# Generated by Django 5.2.11 on 2026-04-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthassessment',
            name='scan_image',
            field=models.ImageField(blank=True, null=True, upload_to='health_scans/'),
        ),
    ]
