# Generated by Django 5.2.11 on 2026-04-17 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_healthassessment_scan_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthassessment',
            options={'ordering': ['-assessment_date']},
        ),
    ]
