# Generated by Django 5.2.11 on 2026-04-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_alter_healthassessment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthassessment',
            name='care_recommendations',
            field=models.TextField(blank=True, help_text='AI generated care recommendations.'),
        ),
        migrations.AddField(
            model_name='healthassessment',
            name='symptom_details',
            field=models.TextField(blank=True, help_text='Optional symptom details provided by user.'),
        ),
    ]
