# Generated by Django 5.0.3 on 2026-05-04 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_healthassessment_care_recommendations_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=100)),
                ('species', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat')], max_length=20)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('last_seen_location', models.CharField(max_length=255)),
                ('last_seen_date', models.DateTimeField()),
                ('photo', models.ImageField(upload_to='missing_pets/')),
                ('contact_phone', models.CharField(max_length=20)),
                ('is_found', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missing_pets', to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missing_reports', to='pets.pet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PetSighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sighting_location', models.CharField(max_length=255)),
                ('sighting_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='sightings/')),
                ('contact_info', models.CharField(help_text='Contact of the person who saw the pet', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('missing_pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sightings', to='pets.missingpet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
