# Generated by Django 5.0.3 on 2026-05-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_missingpet_petsighting'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingpet',
            name='last_seen_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missingpet',
            name='last_seen_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
