# Generated by Django 5.2.11 on 2026-05-24 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_missingpet_last_seen_lat_missingpet_last_seen_lng'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingPetNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('missing_reported', 'Missing pet reported'), ('sighting_reported', 'Sighting reported'), ('marked_found', 'Pet marked found'), ('reopened_missing', 'Missing report reopened')], max_length=30)),
                ('title', models.CharField(max_length=160)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('missing_pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='pets.missingpet')),
                ('sighting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='pets.petsighting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missing_pet_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
