# Generated by Django 5.2.11 on 2026-03-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BreedInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat')], max_length=20)),
                ('breed_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('typical_weight_min_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('typical_weight_max_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperament', models.CharField(blank=True, max_length=255)),
                ('grooming_needs', models.TextField(blank=True)),
                ('exercise_needs', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Breed information',
                'verbose_name_plural': 'Breed information',
                'unique_together': {('species', 'breed_name')},
            },
        ),
        migrations.CreateModel(
            name='DiseaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat')], max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('common_symptoms', models.TextField()),
                ('prevention', models.TextField(blank=True)),
                ('treatment', models.TextField(blank=True)),
            ],
            options={
                'unique_together': {('species', 'name')},
            },
        ),
        migrations.CreateModel(
            name='VaccinationScheduleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat')], max_length=20)),
                ('vaccine_name', models.CharField(max_length=100)),
                ('recommended_age_weeks', models.PositiveIntegerField(help_text='Recommended age in weeks for first dose.')),
                ('repeat_interval_weeks', models.PositiveIntegerField(blank=True, help_text='Interval for booster doses, if applicable.', null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Vaccination schedule template',
                'unique_together': {('species', 'vaccine_name', 'recommended_age_weeks')},
            },
        ),
    ]
