# Generated by Django 5.0.3 on 2026-05-01 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0002_vetdoctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareAdvisory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('both', 'Dog & Cat')], default='both', max_length=20)),
                ('category', models.CharField(choices=[('vaccination', 'Vaccination schedule'), ('diet', 'Diet & nutrition'), ('grooming', 'Grooming practices'), ('hygiene', 'Hygiene care'), ('parasite', 'Parasite prevention'), ('treatment', 'Treatment suggestions')], max_length=30)),
                ('title', models.CharField(max_length=160)),
                ('short_summary', models.CharField(blank=True, max_length=255)),
                ('recommendation', models.TextField()),
                ('when_to_apply', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Care advisory',
                'verbose_name_plural': 'Care advisories',
                'ordering': ['category', 'species', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PetService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('service_type', models.CharField(choices=[('vet', 'Veterinary clinic'), ('groomer', 'Groomer'), ('trainer', 'Trainer'), ('boarding', 'Boarding'), ('pharmacy', 'Pet pharmacy')], max_length=30)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('opening_hours', models.CharField(blank=True, max_length=160)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['city', 'service_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MedicineRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('both', 'Dog & Cat')], default='both', max_length=20)),
                ('condition_name', models.CharField(max_length=150)),
                ('medicine_name', models.CharField(max_length=150)),
                ('dosage_guidance', models.TextField(help_text='Use vet-safe guidance only. Avoid exact dosage unless prescribed.')),
                ('administration_notes', models.TextField(blank=True)),
                ('warnings', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['species', 'condition_name', 'medicine_name'],
                'unique_together': {('species', 'condition_name', 'medicine_name')},
            },
        ),
    ]
