# Generated by Django 5.0.3 on 2026-05-04 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0006_servicebooking'),
        ('pets', '0004_healthassessment_care_recommendations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='pet',
            field=models.ForeignKey(blank=True, help_text='The pet this booking is for.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='pets.pet'),
        ),
    ]
