# Generated by Django 5.0.3 on 2026-05-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0007_servicebooking_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='admin_notes',
            field=models.TextField(blank=True, help_text="Admin's notes or cancellation reason"),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='notes',
            field=models.TextField(blank=True, help_text="User's notes for the booking"),
        ),
    ]
