# Generated by Django 5.2.11 on 2026-05-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0010_customerreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerreview',
            name='admin_reply',
            field=models.TextField(blank=True),
        ),
    ]
