# Generated by Django 5.0.3 on 2026-05-01 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_healthassessment_care_recommendations_and_more'),
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('reminder_type', models.CharField(choices=[('vaccination', 'Vaccination'), ('grooming', 'Grooming'), ('training', 'Training'), ('medical', 'Medical visit'), ('follow_up', 'Follow-up'), ('custom', 'Custom')], default='custom', max_length=30)),
                ('due_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='pets.pet')),
            ],
            options={
                'ordering': ['is_completed', 'due_date', 'title'],
            },
        ),
    ]
