# Generated by Django 5.2.11 on 2026-05-10 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
