# Generated by Django 5.2.11 on 2026-05-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_reminder_push_sent_at_pushnotificationtoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reminder',
            options={'ordering': ['is_completed', 'due_date', 'due_time', 'title']},
        ),
        migrations.AddField(
            model_name='reminder',
            name='due_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
